[profile.default]
src = "src"
out = "out"
libs = ["./lib"]
remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts-upgradeable/lib/openzeppelin-contracts/contracts/",
    "@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/",
    '@chainlink/contracts/=lib/chainlink-brownie-contracts/contracts/src/',
]

# below settings are for OZ upgrades plugins https://docs.openzeppelin.com/upgrades-plugins/1.x/foundry-defender
ffi = true
ast = true
build_info = true
extra_output = ["storageLayout"]

[rpc.endpoints]
mainnet = "${MAINNET_RPC_URL}"
sepolia = "${SEPOLIA_RPC_URL}"

[etherscan]
mainnet = { key = "${ETHERSCAN_API_KEY}" }
sepolia = { key = "${ETHERSCAN_API_KEY}" }
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
